In [1]:
# Soduku grid
grid = [[7,0,0,4,0,2,1,0,0],
        [3,0,1,0,7,9,2,0,0],
        [0,9,0,0,0,1,0,0,0],
        [0,0,0,0,0,0,0,0,8],
        [8,0,6,0,0,0,7,0,0],
        [0,0,0,0,0,0,3,6,0],
        [2,0,0,0,1,5,8,0,0],
        [0,0,5,0,0,3,0,0,0],
        [0,0,0,0,0,0,0,5,7]
        ]

In [2]:
import numpy as np
print(np.matrix(grid))

[[7 0 0 4 0 2 1 0 0]
 [3 0 1 0 7 9 2 0 0]
 [0 9 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 8]
 [8 0 6 0 0 0 7 0 0]
 [0 0 0 0 0 0 3 6 0]
 [2 0 0 0 1 5 8 0 0]
 [0 0 5 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 5 7]]


In [3]:
def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid [y0+i][x0+j] == n:
                return False
    return True   

In [4]:
possible(4,4,5)

True

In [5]:
# Now lets write a solver method
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input('More?')


In [ ]:
solve()

[[7 5 8 4 3 2 1 9 6]
 [3 4 1 6 7 9 2 8 5]
 [6 9 2 5 8 1 4 7 3]
 [1 2 9 3 6 7 5 4 8]
 [8 3 6 1 5 4 7 2 9]
 [5 7 4 2 9 8 3 6 1]
 [2 6 7 9 1 5 8 3 4]
 [9 8 5 7 4 3 6 1 2]
 [4 1 3 8 2 6 9 5 7]]
More?
[[7 5 8 4 3 2 1 9 6]
 [3 4 1 6 7 9 2 8 5]
 [6 9 2 5 8 1 4 7 3]
 [1 2 9 3 6 7 5 4 8]
 [8 3 6 2 5 4 7 1 9]
 [5 7 4 1 9 8 3 6 2]
 [2 6 7 9 1 5 8 3 4]
 [9 8 5 7 4 3 6 2 1]
 [4 1 3 8 2 6 9 5 7]]
More?
[[7 5 8 4 3 2 1 9 6]
 [3 4 1 6 7 9 2 8 5]
 [6 9 2 5 8 1 4 7 3]
 [1 3 9 2 6 7 5 4 8]
 [8 2 6 3 5 4 7 1 9]
 [5 7 4 1 9 8 3 6 2]
 [2 6 7 9 1 5 8 3 4]
 [9 8 5 7 4 3 6 2 1]
 [4 1 3 8 2 6 9 5 7]]
